name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.build.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        env:
          NODE_ENV: production
          VITE_APP_META_TITLE: ${{ vars.VITE_APP_META_TITLE }}
          VITE_APP_META_DESCRIPTION: ${{ vars.VITE_APP_META_DESCRIPTION }}
          VITE_APP_OG_IMAGE: ${{ vars.VITE_APP_OG_IMAGE }}
          VITE_APP_GSV: ${{ secrets.VITE_APP_GSV }}
          VITE_APP_GA: ${{ secrets.VITE_APP_GA }}
          VITE_APP_GA_ID: ${{ vars.VITE_APP_GA_ID }}
          VITE_APP_TWITTER: ${{ vars.VITE_APP_TWITTER }}
          VITE_APP_CANONICAL_URL: ${{ vars.VITE_APP_CANONICAL_URL }}
          VITE_SITE_URL: ${{ vars.VITE_SITE_URL }}
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
